### ISSUE TITLE
Question: where is the data file read?

### ISSUE THREAD

**Issue by vsoch** [ImperialCollegeLondon/research-software-directory#4]
heyo! So I am aware of the data repository here: https://github.com/ImperialCollegeLondon/research-software-directory-data/blob/master/repos.csv, but I don't see how the static site rendered actually gets that file. Is it provided by some service and compressed into the javascript somewhere? I'm hoping to turn this into a jekyll site that can just parse GitHub repos from an org without the data file, but I'm trying to understand how it's currently working. Thank you!

**Comment by vsoch** [comment]
Oh I think I see - you created an account on alogia and then need to upload that data file in the interface, and then provide the application id and api key. I don't think that's super GitHub friendly, at least in how I was imagining it :/ It's too bad the nice interface is coupled with that service, it would be much nicer to not require that.

**Comment by mwoodbri** [comment]
Agreed regarding desirability of a self-hosted solution - Algolia was purely for MVP. For a fully-featured solution I definitely recommend taking a look at https://github.com/research-software-directory/research-software-directory/.

**Comment by vsoch** [comment]
Thanks! I'm going to make one that doesn't require it.

**Comment by vsoch** [comment]
Thanks again! I created one that works natively on GitHub pages (rendering repos from a user or organization) and this could very easily be adopted for a data file too. It looks like yours is working great, so definitely no need to do this, but if you have a user / lab that needs something along these lines (and doesn't want the Alogia dependency) I just shared a write up with the repository: https://twitter.com/vsoch/status/1234226445511090176
